package com.pyra.krpytapplication.incognitokeyboard

import android.content.Context
import com.pyra.krpytapplication.R
import java.util.*

class KeyboardKeyList internal constructor(var context: Context) {
    @JvmField
    var alphaKeyboardKeyList = ArrayList<String>()
    @JvmField
    var symbolKeyboardKeyList1 = ArrayList<String>()
    @JvmField
    var symbolKeyboardKeyList2 = ArrayList<String>()
    private fun setAlphaKeyboardKeyList() {
        alphaKeyboardKeyList.add("1")
        alphaKeyboardKeyList.add("2")
        alphaKeyboardKeyList.add("3")
        alphaKeyboardKeyList.add("4")
        alphaKeyboardKeyList.add("5")
        alphaKeyboardKeyList.add("6")
        alphaKeyboardKeyList.add("7")
        alphaKeyboardKeyList.add("8")
        alphaKeyboardKeyList.add("9")
        alphaKeyboardKeyList.add("0")
        alphaKeyboardKeyList.add("q")
        alphaKeyboardKeyList.add("w")
        alphaKeyboardKeyList.add("e")
        alphaKeyboardKeyList.add("r")
        alphaKeyboardKeyList.add("t")
        alphaKeyboardKeyList.add("y")
        alphaKeyboardKeyList.add("u")
        alphaKeyboardKeyList.add("i")
        alphaKeyboardKeyList.add("o")
        alphaKeyboardKeyList.add("p")
        alphaKeyboardKeyList.add("a")
        alphaKeyboardKeyList.add("s")
        alphaKeyboardKeyList.add("d")
        alphaKeyboardKeyList.add("f")
        alphaKeyboardKeyList.add("g")
        alphaKeyboardKeyList.add("h")
        alphaKeyboardKeyList.add("j")
        alphaKeyboardKeyList.add("k")
        alphaKeyboardKeyList.add("l")
        alphaKeyboardKeyList.add("")
        alphaKeyboardKeyList.add("z")
        alphaKeyboardKeyList.add("x")
        alphaKeyboardKeyList.add("c")
        alphaKeyboardKeyList.add("v")
        alphaKeyboardKeyList.add("b")
        alphaKeyboardKeyList.add("n")
        alphaKeyboardKeyList.add("m")
        alphaKeyboardKeyList.add("")
        alphaKeyboardKeyList.add("")
        alphaKeyboardKeyList.add(",")
        alphaKeyboardKeyList.add("")
        alphaKeyboardKeyList.add(".")
    }

    private fun setSymbolKeyboardKeyList1() {
        symbolKeyboardKeyList1.add("1")
        symbolKeyboardKeyList1.add("2")
        symbolKeyboardKeyList1.add("3")
        symbolKeyboardKeyList1.add("4")
        symbolKeyboardKeyList1.add("5")
        symbolKeyboardKeyList1.add("6")
        symbolKeyboardKeyList1.add("7")
        symbolKeyboardKeyList1.add("8")
        symbolKeyboardKeyList1.add("9")
        symbolKeyboardKeyList1.add("0")
        symbolKeyboardKeyList1.add("+")
        symbolKeyboardKeyList1.add("x")
        symbolKeyboardKeyList1.add(context.getString(R.string.keyboard_key_division_sign))
        symbolKeyboardKeyList1.add("=")
        symbolKeyboardKeyList1.add("/")
        symbolKeyboardKeyList1.add("_")
        symbolKeyboardKeyList1.add(context.getString(R.string.keyboard_key_dollar))
        symbolKeyboardKeyList1.add(context.getString(R.string.keyboard_key_euro))
        symbolKeyboardKeyList1.add(context.getString(R.string.keyboard_key_pound))
        symbolKeyboardKeyList1.add(context.getString(R.string.keyboard_key_indian_rupee))
        symbolKeyboardKeyList1.add("!")
        symbolKeyboardKeyList1.add("@")
        symbolKeyboardKeyList1.add("#")
        symbolKeyboardKeyList1.add("%")
        symbolKeyboardKeyList1.add("^")
        symbolKeyboardKeyList1.add("&")
        symbolKeyboardKeyList1.add("*")
        symbolKeyboardKeyList1.add("(")
        symbolKeyboardKeyList1.add(")")
        symbolKeyboardKeyList1.add("")
        symbolKeyboardKeyList1.add("-")
        symbolKeyboardKeyList1.add("'")
        symbolKeyboardKeyList1.add(context.getString(R.string.keyboard_key_double_quote))
        symbolKeyboardKeyList1.add(":")
        symbolKeyboardKeyList1.add(";")
        symbolKeyboardKeyList1.add(",")
        symbolKeyboardKeyList1.add("?")
        symbolKeyboardKeyList1.add("")
        symbolKeyboardKeyList1.add("")
        symbolKeyboardKeyList1.add(",")
        symbolKeyboardKeyList1.add("")
        symbolKeyboardKeyList1.add(".")
    }

    private fun setSymbolKeyboardKeyList2() {
        symbolKeyboardKeyList2.add("1")
        symbolKeyboardKeyList2.add("2")
        symbolKeyboardKeyList2.add("3")
        symbolKeyboardKeyList2.add("4")
        symbolKeyboardKeyList2.add("5")
        symbolKeyboardKeyList2.add("6")
        symbolKeyboardKeyList2.add("7")
        symbolKeyboardKeyList2.add("8")
        symbolKeyboardKeyList2.add("9")
        symbolKeyboardKeyList2.add("0")
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_backwardslash))
        symbolKeyboardKeyList2.add("<")
        symbolKeyboardKeyList2.add(">")
        symbolKeyboardKeyList2.add("[")
        symbolKeyboardKeyList2.add("]")
        symbolKeyboardKeyList2.add("{")
        symbolKeyboardKeyList2.add("}")
        symbolKeyboardKeyList2.add("`")
        symbolKeyboardKeyList2.add("~")
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_squareroot))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_infinity))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_pi))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_superscript_zero))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_not_equal))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_spade))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_heart))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_diamond))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_clover))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_star))
        symbolKeyboardKeyList2.add("")
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_registered))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_copyright))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_currency_sign))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_much_less))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_much_greater))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_inverted_exclamationmark))
        symbolKeyboardKeyList2.add(context.getString(R.string.keyboard_key_inverted_questionmark))
        symbolKeyboardKeyList2.add("")
        symbolKeyboardKeyList2.add("")
        symbolKeyboardKeyList2.add(",")
        symbolKeyboardKeyList2.add("")
        symbolKeyboardKeyList2.add(".")
    }

    init {
        setAlphaKeyboardKeyList()
        setSymbolKeyboardKeyList1()
        setSymbolKeyboardKeyList2()
    }
}